# Generated by Django 2.2.16 on 2022-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], default='USER', max_length=10),
        ),
    ]
