# Generated by Django 2.2.16 on 2022-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20221122_0730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "USER"),
                    ("MODERATOR", "MODERATOR"),
                    ("ADMIN", "ADMIN"),
                ],
                default="USER",
                max_length=16,
            ),
        ),
    ]
